# ============================================================================
# Project Handlers: Naman Sain & Souvik Mallik
# 
# Maintainers:
# - Naman Sain   : ROS FULL STACK and Development with Software to Hardware Communication
# - Souvik Mallik: Embedded Maintainer
# ============================================================================

TrajectoryPlannerROS:
  max_vel_x: 0.105
  min_vel_x: 0.06
  max_vel_theta: 0.35
  min_vel_theta: -0.35
  min_in_place_vel_theta: 0.15
  acc_lim_x: 0.5
  acc_lim_theta: 1.5
  holonomic_robot: false

  yaw_goal_tolerance: 0.25
  xy_goal_tolerance: 0.10
  latch_xy_goal_tolerance: true

  sim_time: 3.0
  sim_granularity: 0.02
  angular_sim_granularity: 0.02
  vx_samples: 20
  vtheta_samples: 40

  meter_scoring: true
  pdist_scale: 0.6
  gdist_scale: 1.0
  occdist_scale: 0.02
  heading_lookahead: 0.4
  heading_scoring: false
  dwa: true

  oscillation_reset_dist: 0.10
  publish_cost_grid_pc: false
