# ============================================================================
# Project Handlers: Naman Sain & Souvik Mallik
# 
# Maintainers:
# - Naman Sain   : ROS FULL STACK and Development with Software to Hardware Communication
# - Souvik Mallik: Embedded Maintainer
# ============================================================================

frequency: 20
sensor_timeout: 0.2
two_d_mode: true
transform_time_offset: 0.05
transform_timeout: 0.2
publish_tf: true
publish_acceleration: false

map_frame: map
odom_frame: odom
base_link_frame: base_footprint
world_frame: odom

odom0: /wheel/odom
odom0_config: [false, false, false,
               false, false, false,
               true,  false, false,
               false, false, true,
               false, false, false]
odom0_differential: false
odom0_relative: false
odom0_queue_size: 10

# IMU fusion ENABLED — BNO055 provides reliable absolute orientation (Quaternions).
imu0: /imu/data_raw
imu0_config: [false, false, false,
              false, false, true,
              false, false, false,
              false, false, false,
              false, false, false]
imu0_differential: false
imu0_relative: true
imu0_queue_size: 10
imu0_remove_gravitational_acceleration: false
